export let answers = [
    "Signs point to a resounding yes.",
    "It's in the realm of possibility.",
    "The future looks promising.",
    "All indications are positive.",
    "The odds are in your favor.",
    "Count on it like the rising sun.",
    "Absolutely and without a doubt.",
    "The answer lies within your grasp.",
    "It's a definite go.",
    "Without question, yes.",
    "The stars align in your favor.",
    "It's written in the cosmic script.",
    "The universe whispers yes.",
    "The outlook is brilliant.",
    "Fate smiles upon you.",
    "Your dreams will materialize.",
    "The tide of fortune turns in your favor.",
    "The answer is crystal clear—yes!",
    "It's a slam dunk.",
    "The energy flows in your direction.",
    "The signs are pointing to a positive outcome.",
    "The magic eight ball says absolutely.",
    "The universe nods in agreement.",
    "You have the Midas touch.",
    "Your intuition confirms it—yes.",
    "Luck is on your side.",
    "The path is paved with success.",
    "It's a green light all the way.",
    "The answer dances on the horizon—yes.",
    "The cosmos conspires in your favor.",
    "It's a certainty that cannot be denied.",
    "The vibrations are in alignment—yes.",
    "Destiny beckons with open arms.",
    "The answer is woven into the fabric of time—yes.",
    "The universe bestows its blessings.",
    "It's a resounding affirmation—yes.",
    "The answer lies within the whispers of the wind.",
    "The future unfolds with a positive outcome.",
    "Fortune favors the bold—you shall succeed.",
    "The stars sing your victory.",
    "It's a cosmic yes.",
    "The universe applauds your efforts.",
    "It's a surefire yes.",
    "Serendipity smiles upon you.",
    "The answer blooms like a radiant flower—yes.",
    "The tapestry of fate weaves in your favor.",
    "The answer is an echo of your desires—yes.",
    "Destiny reveals its secrets—you will prevail.",
    "The universe nods with unwavering certainty.",
    "The answer is a resounding chorus of yes.",
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes – definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "Outlook not so good.",
    "My sources say no.",
    "Very doubtful.",
    "My reply is no.",
    "Outlook is bleak.",
    "Chances aren’t good.",
    "Very unlikely.",
    "Odds are not in your favor.",
    "Not looking good.",
    "It’s not likely.",
    "I’m afraid not.",
    "I don't think so.",
    "Not a chance.",
    "No way.",
    "Sorry, no.",
    "Unfortunately no.",
    "Nope.",
    "Definitely not.",
    "It is unlikely.",
    "It is impossible.",
    "The outlook is murky.",
    "Cannot say now.",
    "The signs are unclear.",
    "It’s hard to say.",
    "The answer is within you.",
    "It's not my place to say.",
    "Perhaps you already know the answer.",
    "I have faith in you to make the right choice.",
    "It’s up to you to decide.",
    "You will know when the time is right.",
    "The future is unwritten.",
    "Time will tell.",
    "You have the power to change the outcome.",
    "Trust your instincts.",
    "Listen to your heart.",
    "Take a leap of faith.",
    "The universe has a plan.",
    "Don't give up.",
    "Keep trying.",
    "You can do it.",
    "Believe in yourself.",
    "You have what it takes.",
    "Stay positive.",
    "Stay focused on your goals.",
    "Stay true to yourself.",
    "Have faith in the journey.",
    "Be patient.",
    "Everything happens for a reason.",
    "Good things come to those who wait.",
    "The best is yet to come.",
    "This too shall pass.",
    "Change is on the horizon.",
    "A new door will open soon.",
    "Opportunities are coming.",
    "The tide is turning.",
    "The winds of change are blowing.",
    "You are stronger than you know.",
    "You are capable of amazing things.",
    "You are loved.",
    "You are not alone.",
    "Someone cares about you deeply.",
    "Everything will be okay.",
    "You are on the right path.",
    "You are exactly where you need to be.",
    "Trust the journey.",
    "You are making progress.",
    "You are doing your best.",
    "You are enough.",
    "Believe in yourself and all that you are.",
    "Your potential is limitless.",
    "You are a force to be reckoned with.",
    "You are destined for greatness.",
    "Dream big and go for it.",
    "Success is within reach.",
    "The world is your oyster.",
    "Anything is possible.",
    "You can achieve anything you set your mind to.",
    "Keep reaching for the stars.",
    "Never give up on your dreams.",
    "Stay true to your passions.",
    "Your hard work will pay off.",
    "The cosmic forces align in your favor.",
    "The answer emerges from the depths of possibility.",
    "It's a definite and resounding yes.",
    "The universe whispers sweet affirmations.",
    "The signs point to an undeniable outcome.",
    "The winds of destiny carry a positive reply.",
    "Without a doubt, the answer is yes.",
    "It's like finding a hidden treasure—yes.",
    "The universe nods approvingly.",
    "The answer is written in the constellations.",
    "You can bet your luck on it—yes.",
    "It's as certain as the sunrise.",
    "The future holds an unequivocal yes.",
    "The cosmic dice roll in your favor.",
    "The harmony of the universe confirms it—yes.",
    "The stars shower you with affirmative light.",
    "The answer blooms with unwavering certainty.",
    "Trust in the cosmic wink—it's a yes.",
    "The universe conspires to grant your wish.",
    "The celestial symphony sings a resounding yes.",
    "It's a clear and unambiguous yes.",
    "The universe unfolds its positive plan.",
    "It's etched in the tapestry of fate—yes.",
    "The cosmos grants your heart's desire.",
    "The answer dances on the cosmic stage—yes.",
    "Serendipity smiles upon you without hesitation.",
    "The universe blesses your endeavor.",
    "The answer shines like a radiant star—yes.",
    "Destiny applauds your intentions—it's a yes.",
    "The universal energy aligns with your aspirations.",
    "It's a cosmic high-five of affirmation.",
    "The answer emerges from the depths of the unknown.",
    "Fate extends its helping hand—it's a yes.",
    "The cosmic puzzle completes with a resounding yes.",
    "The stars paint a picture of positivity.",
    "Destiny's compass points in your direction—it's a yes.",
    "The universe's secret whispers affirm your hopes.",
    "The celestial signs herald a definite yes.",
    "The answer echoes in the halls of destiny.",
    "The universe bestows its blessings upon you.",
    "The cosmic dice roll in your favor—it's a yes.",
    "Serendipity dances to the rhythm of affirmation.",
    "The answer materializes with celestial approval.",
    "The universe gifts you a resounding yes.",
    "Fate's tapestry weaves in your favor—it's a yes.",
    "The cosmic symphony sings your praises.",
    "The answer sparkles like stardust—yes.",
    "Destiny's gates swing open to reveal a positive outcome.",
    "The universe's grand design includes a resounding yes.",
    "It's a harmonious chorus of affirmation.",
    "The celestial alignment guarantees a positive response.",
    "The answer shines brightly from the cosmos—yes.",
    "Destiny's scales tip in your favor—it's a yes.",
    "The universe's favor is bestowed upon you.",
    "Serendipity dances in your footsteps—it's a yes.",
    "The celestial oracle reveals a positive outcome.",
    "The answer resonates with cosmic approval.",
    "Fate's compass points unswervingly—it's a yes.",
    "The universe's whispers carry affirmative promises.",
    "The cosmic forces unite to deliver a resounding yes.",
    "Destiny's path leads you to a positive outcome.",
    "The answer bursts forth like a supernova—yes.",
    "The celestial spotlight shines upon your desires—it's a yes.",
    "The universe's stars align in your favor.",
    "Serendipity's magic weaves a tapestry of yes.",
    "The answer is etched in the scrolls of fate.",
    "Destiny's gavel strikes in your favor—it's a yes.",
    "The celestial river carries your dreams to fulfillment.",
    "The universe's blessings shower upon you—it's a yes.",
    "The cosmic compass points towards a positive outcome.",
    "The answer rings true in the celestial chambers.",
    "Fate's door swings open—it's a yes.",
    "The universe's hand guides you towards success.",
    "Serendipity's embrace confirms your aspirations—it's a yes.",
    "The answer echoes through the cosmic expanse.",
    "Destiny's stars twinkle with approval—it's a yes.",
    "The celestial tapestry weaves a positive outcome.",
    "The universe's threads intertwine to deliver a resounding yes.",
    "The cosmic energy propels you towards a positive answer.",
    "Fate's scales balance in your favor—it's a yes.",
    "The answer reverberates with cosmic affirmation.",
    "The universe's symphony sings your praises—it's a yes.",
    "Serendipity's touch seals your fate with a positive outcome.",
    "The celestial confluence guarantees a resounding yes.",
    "Destiny's wheel spins in your favor—it's a yes.",
    "The universe's guiding hand ushers you towards success.",
    "The answer dances on the cosmic breeze.",
    "Fate's compass points unwaveringly—it's a yes.",
    "The cosmic web weaves a tapestry of positivity.",
    "The universe's blessings rain upon you—it's a yes.",
    "Serendipity's path leads you to a positive outcome.",
    "The answer radiates with celestial approval.",
    "Destiny's stars align to deliver a resounding yes.",
    "The celestial embrace envelops your dreams—it's a yes.",
    "The universe's currents carry you towards success.",
    "The cosmic dance choreographs a positive answer.",
    "Fate's hand tips the scales—it's a yes.",
    "The answer echoes in the cosmic chorus of affirmation.",
    "The answer resonates with celestial approval.",
    "Destiny's compass points towards a positive outcome.",
    "The celestial symphony sings your praises—it's a yes.",
    "Serendipity's magic guides your path to success.",
    "The answer gleams with celestial certainty.",
    "The universe nods with resolute agreement—it's a yes.",
    "Fate's strings are finely tuned in your favor.",
    "The cosmic energy fuels your dreams—it's a yes.",
    "The answer ignites a beacon of affirmation.",
    "The universe's melody resonates with positive vibrations.",
    "Destiny's map unfolds with a clear path—it's a yes.",
    "Serendipity's touch blesses your journey.",
    "The answer echoes through the celestial realms—it's a yes.",
    "The universe's constellations align for your triumph.",
    "Fate's clock ticks towards a positive outcome.",
    "The cosmic tides carry you to a resounding yes.",
    "The answer dances in the realm of possibilities.",
    "The universe's spotlight shines upon your desires—it's a yes.",
    "Serendipity's whispers guide you to a positive answer.",
    "Destiny's doors swing wide open—it's a yes.",
    "The celestial chorus sings your praises with certainty.",
    "The answer emerges from the cosmic depths—it's a yes.",
    "The universe's embrace envelops your dreams in affirmation.",
    "Fate's hand gently nudges you towards success—it's a yes.",
    "The cosmic symphony orchestrates a positive outcome.",
    "The answer glimmers with celestial approval.",
    "The celestial river carries you towards fulfillment—it's a yes.",
    "The universe's currents converge in your favor.",
    "Serendipity's touch seals your fate with positivity.",
    "The answer resonates in the cosmic harmony.",
    "Fate's whispers confirm a positive outcome—it's a yes.",
    "The cosmic puzzle pieces fit together—it's a resounding yes.",
    "The universe's magic works in your favor.",
    "The answer emerges like a shooting star—it's a yes.",
    "Destiny's wind fills your sails with affirmation.",
    "The celestial canvas paints a picture of positivity.",
    "The universe's compass points in your direction—it's a yes.",
    "Serendipity's touch guides you towards a positive answer.",
    "The answer sparkles in the cosmic night sky—it's a yes.",
    "Fate's wheels turn in your favor.",
    "The cosmic symphony heralds a positive outcome—it's a yes.",
    "The universe's gaze is fixed upon your success.",
    "The answer floats on the cosmic breeze of affirmation.",
    "Destiny's footsteps lead you to a resounding yes.",
    "The celestial tapestry weaves a story of positivity.",
    "The universe's blessings rain down upon you—it's a yes.",
    "Serendipity's embrace seals your fate with a positive outcome.",
    "The cosmic realm nods in agreement—it's a yes.",
    "Destiny's path unfolds with a positive outcome.",
    "The universe's threads intertwine to manifest a resounding yes.",
    "Serendipity's touch blesses your journey—it's a yes.",
    "The answer radiates with celestial certainty.",
    "Fate's tapestry weaves in your favor—it's a definite yes.",
    "The cosmic energies align to deliver a positive response.",
    "The universe's whispers carry the affirmation you seek.",
    "The answer resonates in the celestial symphony—it's a resounding yes.",
    "Destiny's map leads you to a positive outcome—it's written in the stars.",
    "The universe's embrace envelops your dreams with a resounding yes.",
    "Serendipity dances on the edge of your intentions—it's a yes.",
    "The answer illuminates the cosmic expanse with certainty.",
    "Fate's hand gently guides you towards success—it's a yes.",
    "The cosmic currents carry you towards a positive answer.",
    "The universe's tapestry weaves a story of affirmation.",
    "The answer echoes through the celestial realms—it's a definite yes.",
    "Destiny's compass points unwaveringly in your favor.",
    "The universe's blessings rain upon your path—it's a resounding yes.",
    "The answer sparkles like stardust in the cosmic void—it's a yes.",
    "Fate's scales balance in your favor—it's destined to be a yes.",
    "The cosmic energy aligns with your intentions—it's a resounding yes.",
    "The universe's guiding hand ushers you towards a positive answer.",
    "The answer dances in harmony with the celestial rhythm—it's a yes.",
    "The celestial chorus sings your praises—it's a definite yes.",
    "The answer blooms like a celestial flower of affirmation.",
    "The universe's currents carry you towards the shores of success—it's a yes.",
    "Serendipity's touch paints your path with positive outcomes.",
    "The answer resonates in the cosmic web—it's a resounding yes.",
    "Fate's tapestry weaves a story of favorable circumstances—it's a yes.",
    "The cosmic forces align to deliver a positive response.",
    "The universe's whispers carry the affirmation you seek—it's a definite yes.",
    "The answer gleams with celestial certainty—it's written in the stars.",
    "Destiny's compass points towards a positive outcome—it's a resounding yes.",
    "The universe's embrace envelops your dreams with unwavering approval.",
    "Serendipity dances on the edge of your intentions—it's a resounding yes.",
    "The answer illuminates the cosmic expanse with unwavering certainty.",
    "Fate's hand gently guides you towards success—it's destined to be a yes.",
    "The cosmic currents carry you towards a positive answer—it's in the cards.",
    "The universe's tapestry weaves a story of unwavering affirmation.",
    "Destiny's compass points unwaveringly in your favor—it's written in the stars.",
    "Serendipity's touch seals your fate with a positive outcome—it's in the stars.",
    "The answer sparkles like stardust in the cosmic void—it's a definite yes.",
    "Fate's scales balance in your favor—it's destined to be a resounding yes.",
    "The cosmic energy aligns with your intentions—it's written in the stars.",
    "The universe's guiding hand ushers you towards a positive answer—it's a yes.",
    "The answer dances in harmony with the celestial rhythm—it's a resounding yes.",
    "Destiny's stars align to deliver a resounding yes—it's written in the stars.",
    "The celestial chorus sings your praises with unwavering certainty—it's a yes.",
    "The answer blooms like a celestial flower of unwavering affirmation.",
    "Serendipity's touch paints your path with positive outcomes—it's in the stars.",
    "The answer resonates in the cosmic web—it's a definite yes.",
    "Fate's tapestry weaves a story of favorable circumstances—it's written in the stars.",
    "The cosmic forces align to deliver a positive response—it's a resounding yes.",
    "The universe's whispers carry the unwavering affirmation you seek—it's a yes.",
    "The answer gleams with celestial certainty—it's destined to be a yes.",
    "The universe's embrace envelops your dreams with unwavering approval—it's in the stars.",
    "The answer illuminates the cosmic expanse with unwavering certainty—it's written in the stars.",
    "The universe's tapestry weaves a story of unwavering affirmation—it's a yes.",
    "The cosmic winds whisper yes in your ear.",
    "Signs point to a positive outcome.",
    "The universe nods in approval—it's a definite yes.",
    "As the stars align, so do your chances of success.",
    "It is written in the celestial scrolls—yes, indeed.",
    "The answer materializes before you with a resounding yes.",
    "Destiny's path illuminates the way—it's a yes.",
    "The cosmic tides carry your dreams to fruition.",
    "The universe conspires in your favor—it's a resounding yes.",
    "The celestial orchestra plays a melody of affirmation—it's a definite yes.",
    "Fate's hand gently guides you towards a positive outcome.",
    "The cosmic forces align to grant your wish—it's written in the stars.",
    "The answer dances in the celestial realm—it's a resounding yes.",
    "The universe bestows its blessings upon your request—it's a yes.",
    "Serendipity weaves a tapestry of positive outcomes—it's in the stars.",
    "The answer shimmers like stardust in the night sky—it's a definite yes.",
    "Fate's scales tip in your favor—it's destined to be a resounding yes.",
    "The universe's guiding hand points you towards a positive answer—it's a yes.",
    "The answer harmonizes with the celestial symphony—it's a resounding yes.",
    "Destiny's stars align to grant your heart's desire—it's written in the stars.",
    "The cosmic choir sings a chorus of affirmation—it's a yes.",
    "The answer blossoms like a celestial flower of unwavering certainty.",
    "Serendipity's touch paints your path with vibrant positive outcomes.",
    "The cosmic forces conspire to deliver a positive response—it's a resounding yes.",
    "The universe's whispers carry the affirmation you seek—it's a yes.",
]

export function get_8ball_answer() {
    let randomNumber = Math.floor(Math.random() * answers.length);
    let randomAnswer = answers[randomNumber];
    return(randomAnswer);
}