let nhie = [
    "Never have I ever traveled to a different continent.",
    "Never have I ever eaten a whole habanero pepper.",
    "Never have I ever bungee jumped.",
    "Never have I ever won a game of poker.",
    "Never have I ever gone scuba diving.",
    "Never have I ever been skydiving.",
    "Never have I ever sung karaoke in front of a large crowd.",
    "Never have I ever ridden a horse.",
    "Never have I ever gone surfing.",
    "Never have I ever tried sushi.",
    "Never have I ever been to a music festival.",
    "Never have I ever dyed my hair a vibrant color.",
    "Never have I ever ridden a roller coaster.",
    "Never have I ever been stung by a bee.",
    "Never have I ever gone camping alone.",
    "Never have I ever run a marathon.",
    "Never have I ever learned to play a musical instrument.",
    "Never have I ever been on a hot air balloon ride.",
    "Never have I ever gone zip-lining.",
    "Never have I ever tried rock climbing.",
    "Never have I ever gone skinny dipping.",
    "Never have I ever performed on stage.",
    "Never have I ever gone on a road trip with friends.",
    "Never have I ever gone snorkeling.",
    "Never have I ever ridden a motorcycle.",
    "Never have I ever gone ice skating.",
    "Never have I ever climbed a mountain.",
    "Never have I ever learned to juggle.",
    "Never have I ever tried acupuncture.",
    "Never have I ever gone fishing.",
    "Never have I ever learned to salsa dance.",
    "Never have I ever slept under the stars.",
    "Never have I ever gone on a blind date.",
    "Never have I ever been to a professional sports game.",
    "Never have I ever tried a extreme sport like paragliding.",
    "Never have I ever volunteered at a homeless shelter.",
    "Never have I ever gone on a cruise.",
    "Never have I ever learned a foreign language.",
    "Never have I ever gone paintballing.",
    "Never have I ever ridden a unicycle.",
    "Never have I ever gone snowboarding.",
    "Never have I ever tried virtual reality gaming.",
    "Never have I ever gone on a helicopter ride.",
    "Never have I ever participated in a talent show.",
    "Never have I ever learned to surf.",
    "Never have I ever gone white-water rafting.",
    "Never have I ever taken a cooking class.",
    "Never have I ever tried to learn how to juggle.",
    "Never have I ever visited a haunted house.",
    "Never have I ever gone on a camping trip without electricity.",
    "Never have I ever gone on a hot air balloon ride.",
    "Never have I ever tried a food from a different culture.",
    "Never have I ever learned to speak a foreign language fluently.",
    "Never have I ever been scuba diving.",
    "Never have I ever tried bungee jumping.",
    "Never have I ever gone parasailing.",
    "Never have I ever been on a cruise ship.",
    "Never have I ever gone skydiving.",
    "Never have I ever participated in a marathon.",
    "Never have I ever gone camping in the wilderness.",
    "Never have I ever tried a new cuisine.",
    "Never have I ever gone salsa dancing.",
    "Never have I ever been to a masquerade ball.",
    "Never have I ever learned to ride a skateboard.",
    "Never have I ever tried kiteboarding.",
    "Never have I ever attended a live theater performance.",
    "Never have I ever gone deep-sea fishing.",
    "Never have I ever learned to sew or knit.",
    "Never have I ever gone on a photography expedition.",
    "Never have I ever tried stand-up comedy.",
    "Never have I ever been in a canoe or kayak.",
    "Never have I ever learned to do magic tricks.",
    "Never have I ever gone on a safari.",
    "Never have I ever tried scuba diving.",
    "Never have I ever gone ice fishing.",
    "Never have I ever learned to play chess.",
    "Never have I ever gone horseback riding on the beach.",
    "Never have I ever gone to a spa for a massage or facial.",
    "Never have I ever tried indoor rock climbing.",
    "Never have I ever gone on a long-distance hiking trip.",
    "Never have I ever tried zip-lining through a rainforest.",
    "Never have I ever gone on a meditation retreat.",
    "Never have I ever gone on a helicopter tour of a city.",
    "Never have I ever tried acroyoga.",
    "Never have I ever gone on a wine tasting tour.",
    "Never have I ever gone deep-sea diving.",
    "Never have I ever gone on a cruise to the Caribbean.",
    "Never have I ever tried snowshoeing.",
    "Never have I ever gone on a sailing trip.",
    "Never have I ever tried deep-sea fishing.",
    "Never have I ever gone on a hot air balloon safari.",
    "Never have I ever tried windsurfing.",
    "Never have I ever gone on a zip line across a canyon.",
    "Never have I ever gone on a helicopter skiing trip.",
    "Never have I ever tried indoor skydiving.",
    "Never have I ever gone on a train journey across multiple countries.",
    "Never have I ever tried paddleboarding.",
    "Never have I ever gone on a camel ride.",
    "Never have I ever tried waterfall rappelling.",
    "Never have I ever gone on a road trip through the desert.",
    "Never have I ever tried wakeboarding.",
    "Never have I ever gone on a dog sledding adventure.",
    "Never have I ever tried indoor surfing.",
    "Never have I ever gone on a hot air balloon ride at sunrise.",
    "Never have I ever tried sandboarding.",
    "Never have I ever gone on a snorkeling trip in the Great Barrier Reef.",
    "Never have I ever tried mountain biking.",
    "Never have I ever gone on a helicopter wine tour.",
    "Never have I ever tried flyboarding.",
    "Never have I ever gone on a cave exploration.",
    "Never have I ever tried paragliding over a beautiful landscape.",
    "Never have I ever gone on a wildlife safari in Africa.",
    "Never have I ever tried stand-up paddleboarding.",
    "Never have I ever gone on a hot air balloon ride over a vineyard.",
    "Never have I ever tried snowmobiling.",
    "Never have I ever gone on a zip line over a waterfall.",
    "Never have I ever gone paragliding.",
    "Never have I ever tried deep-sea diving.",
    "Never have I ever been to a music concert.",
    "Never have I ever gone on a road trip across multiple countries.",
    "Never have I ever gone on a helicopter tour.",
    "Never have I ever tried snowboarding.",
    "Never have I ever tried salsa dancing.",
    "Never have I ever gone on a camping trip.",
    "Never have I ever been to a theme park.",
    "Never have I ever been on a blind date.",
    "Never have I ever tried an extreme sport like paragliding.",
    "Never have I ever tried horseback riding.",
    "Never have I ever gone hiking in the mountains.",
    "Never have I ever tried archery.",
    "Never have I ever gone to a masquerade ball.",
    "Never have I ever gone paddleboarding.",
    "Never have I ever gone on a river rafting trip.",
    "Never have I ever tried jet skiing.",
    "Never have I ever gone on a helicopter tour of a city at night.",
    "Never have I ever tried cave tubing.",
    "Never have I ever gone on a whale-watching tour.",
    "Never have I ever tried sandcastle building on the beach.",
    "Never have I ever gone on a kayaking trip.",
    "Never have I ever tried driving a race car.",
    "Never have I ever gone on a bike tour through a scenic route.",
    "Never have I ever tried water skiing.",
    "Never have I ever gone on a tour of a chocolate factory.",
    "Never have I ever tried cliff jumping.",
    "Never have I ever gone on a dune buggy adventure.",
    "Never have I ever tried heli-skiing.",
    "Never have I ever gone on a wine and cheese tasting tour.",
    "Never have I ever tried sand dune surfing.",
    "Never have I ever gone on a ghost tour.",
    "Never have I ever gone on a segway tour.",
    "Never have I ever tried fly fishing.",
    "Never have I ever gone on a gondola ride in Venice.",
    "Never have I ever tried dog sledding.",
    "Never have I ever gone on a bike tour in a foreign city.",
    "Never have I ever tried bodyboarding.",
    "Never have I ever gone on a yacht excursion.",
    "Never have I ever tried bird watching.",
    "Never have I ever gone on a kayaking trip through a mangrove forest.",
    "Never have I ever tried sand sculpture building.",
    "Never have I ever gone on a jet boat ride.",
    "Never have I ever tried kite surfing.",
    "Never have I ever gone on a wine and painting class.",
    "Never have I ever gone on a helicopter tour of a volcano.",
    "Never have I ever tried archery tag.",
    "Never have I ever gone on a scenic train ride.",
    "Never have I ever tried scuba diving in a cenote.",
    "Never have I ever gone on a hot air balloon ride in Cappadocia.",
    "Never have I ever tried sand dune bashing.",
    "Never have I ever gone on a fishing charter.",
    "Never have I ever tried zorbing.",
    "Never have I ever gone on a river cruise.",
    "Never have I ever tried trampolining.",
    "Never have I ever gone on a kayaking trip to see bioluminescent plankton.",
    "Never have I ever tried paddleboard yoga.",
    "Never have I ever gone on a helicopter tour of a glacier.",
    "Never have I ever tried stand-up paddleboard fishing.",
    "Never have I ever gone on a wine and bike tour.",
    "Never have I ever gone on a hot air balloon ride in Bagan.",
    "Never have I ever gone on a scenic helicopter flight.",
    "Never have I ever tried sandboarding in the desert.",
    "Never have I ever gone on a helicopter tour of the Grand Canyon.",
    "Never have I ever tried slacklining.",
    "Never have I ever gone on a winery tour.",
    "Never have I ever tried parasailing.",
    "Never have I ever tried ice climbing.",
    "Never have I ever tried parkour.",
    "Never have I ever gone on a hot air balloon ride over a waterfall.",
    "Never have I ever gone on a river kayaking trip.",
    "Never have I ever tried wake surfing.",
    "Never have I ever gone on a safari in a national park.",
    "Never have I ever gone on a horseback riding vacation.",
    "Never have I ever tried geocaching.",
    "Never have I ever gone on a motorbike road trip.",
    "Never have I ever tried sailing on a catamaran.",
    "Never have I ever gone on a caving expedition.",
    "Never have I ever tried sand sculpting.",
    "Never have I ever gone on a whitewater rafting adventure.",
    "Never have I ever gone on a helicopter tour of a coral reef.",
    "Never have I ever tried kite making and flying.",
    "Never have I ever gone on a glacier hiking trip.",
    "Never have I ever tried playing paintball in a forest.",
    "Never have I ever gone on a photography safari.",
    "Never have I ever tried tandem skydiving.",
    "Never have I ever gone on a food tour in a foreign country.",
    "Never have I ever tried sandboarding in a desert.",
    "Never have I ever gone on a zip line through a rainforest.",
    "Never have I ever tried making pottery on a pottery wheel.",
    "Never have I ever gone on a horseback riding tour through the countryside.",
    "Never have I ever tried paragliding off a cliff.",
    "Never have I ever gone on a vineyard tour and wine tasting.",
    "Never have I ever tried snowmobiling in the mountains.",
    "Never have I ever gone on a culinary tour in a famous food city.",
    "Never have I ever tried canyoning.",
    "Never have I ever gone on a sunset cruise.",
    "Never have I ever tried axe throwing.",
    "Never have I ever gone on a tour of ancient ruins.",
    "Never have I ever tried skeet shooting.",
    "Never have I ever gone on a cave tubing adventure.",
    "Never have I ever tried paddleboard fishing.",
    "Never have I ever gone on a hot air balloon ride over a desert.",
    "Never have I ever tried sandboarding on a volcano.",
    "Never have I ever gone on a horseback riding trip in the mountains.",
    "Never have I ever tried stand-up paddleboard yoga.",
    "Never have I ever tried fly fishing in a remote river.",
    "Never have I ever gone on a wine and bike tour through vineyards.",
    "Never have I ever tried mountain biking on a challenging trail.",
    "Never have I ever gone on a snorkeling trip in a cenote.",
    "Never have I ever tried bungee jumping off a bridge.",
    "Never have I ever gone on a kayaking trip through a river gorge.",
    "Never have I ever tried sandboarding in a desert oasis.",
    "Never have I ever gone on a helicopter tour of a waterfall.",
    "Never have I ever tried archery in an archery range.",
    "Never have I ever gone on a scenic train ride through a national park.",
    "Never have I ever tried scuba diving in a coral reef.",
    "Never have I ever gone on a hot air balloon ride over a canyon.",
    "Never have I ever tried sand dune bashing in a desert.",
    "Never have I ever gone on a fishing charter in the ocean.",
    "Never have I ever tried zorbing down a hill.",
    "Never have I ever gone on a river cruise through a famous city.",
    "Never have I ever tried trampolining and doing flips.",
    "Never have I ever gone on a kayaking trip to a secluded beach.",
    "Never have I ever tried paddleboard yoga on a calm lake.",
    "Never have I ever gone on a helicopter tour of a mountain range.",
    "Never have I ever tried fly fishing in a crystal-clear stream.",
    "Never have I ever gone on a wine and chocolate tasting tour.",
    "Never have I ever tried sandboarding on a sand dune.",
    "Never have I ever gone on a ghost tour in a haunted city.",
    "Never have I ever tried kiteboarding on a windy beach.",
    "Never have I ever gone on a segway tour of a historical area.",
    "Never have I ever tried fly fishing in a remote lake.",
    "Never have I ever gone on a gondola ride in a romantic city.",
    "Never have I ever tried dog sledding in a snowy landscape.",
    "Never have I ever gone on a bike tour in a foreign countryside.",
    "Never have I ever tried bodyboarding in the ocean waves.",
    "Never have I ever gone on a yacht excursion in a luxury destination.",
    "Never have I ever tried bird watching in a nature reserve.",
    "Never have I ever tried sand sculpture building on a sandy beach.",
    "Never have I ever gone on a jet boat ride in a thrilling river.",
    "Never have I ever tried kite surfing on a windy day.",
    "Never have I ever gone on a wine and painting class with friends.",
    "Never have I ever tried flyboarding on a calm lake.",
    "Never have I ever gone on a helicopter tour of a volcanic crater.",
    "Never have I ever tried archery tag with a group of friends.",
    "Never have I ever gone on a scenic train ride through a scenic route.",
    "Never have I ever tried scuba diving in a colorful coral reef.",
    "Never have I ever gone on a hot air balloon ride over a scenic landscape.",
    "Never have I ever tried sand dune bashing in a desert safari.",
    "Never have I ever gone on a fishing charter in the open sea.",
    "Never have I ever tried zorbing down a hillside.",
    "Never have I ever gone on a river cruise through a historic city.",
    "Never have I ever tried trampolining and attempting acrobatic tricks.",
    "Never have I ever gone on a kayaking trip to explore hidden caves.",
    "Never have I ever tried paddleboard yoga on a peaceful lake.",
    "Never have I ever gone on a helicopter tour of a breathtaking glacier.",
    "Never have I ever tried fly fishing in a remote mountain stream.",
    "Never have I ever gone on a wine and cheese tasting tour in a vineyard.",
    "Never have I ever tried sandboarding on a giant sand dune.",
    "Never have I ever gone on a ghost tour in a historic town.",
    "Never have I ever tried kiteboarding on a windy tropical beach.",
    "Never have I ever gone on a segway tour of a bustling city.",
    "Never have I ever tried fly fishing in a secluded river.",
    "Never have I ever gone on a gondola ride in a charming canal city.",
    "Never have I ever tried dog sledding in a snowy wilderness.",
    "Never have I ever gone on a bike tour through scenic countryside.",
    "Never have I ever tried bodyboarding in crashing ocean waves.",
    "Never have I ever gone on a yacht excursion to explore hidden islands.",
    "Never have I ever tried bird watching in a serene nature sanctuary.",
    "Never have I ever gone on a kayaking trip to spot dolphins in the wild.",
    "Never have I ever tried sand sculpture building on a pristine beach.",
    "Never have I ever gone on a jet boat ride along a thrilling river.",
    "Never have I ever tried kite surfing on a windy tropical coastline.",
    "Never have I ever gone on a wine and pottery class to create unique pieces.",
    "Never have I ever tried flyboarding and performing tricks in the air.",
    "Never have I ever gone on a helicopter tour of a majestic mountain range.",
    "Never have I ever gone on a scenic train ride through breathtaking landscapes.",
    "Never have I ever tried scuba diving to explore a sunken shipwreck.",
    "Never have I ever gone on a hot air balloon ride over a stunning natural wonder.",
    "Never have I ever tried sand dune bashing in a desert off-road adventure.",
    "Never have I ever gone on a fishing charter in the deep sea.",
    "Never have I ever tried zorbing down a hill in a giant inflatable ball.",
    "Never have I ever gone on a river cruise to admire architectural marvels.",
    "Never have I ever tried trampolining and attempting flips and somersaults.",
    "Never have I ever gone on a kayaking trip to explore hidden lagoons.",
    "Never have I ever tried paddleboard yoga on a calm and serene lake.",
    "Never have I ever gone on a helicopter tour of a pristine icefield.",
    "Never have I ever tried fly fishing in a remote and untouched river.",
    "Never have I ever gone on a wine and chocolate tasting tour at a vineyard.",
    "Never have I ever tried sandboarding on a towering sand dune.",
    "Never have I ever gone on a ghost tour in a haunted historic city.",
    "Never have I ever tried kiteboarding on a windy and picturesque beach.",
    "Never have I ever gone on a segway tour of a vibrant and bustling city.",
    "Never have I ever tried fly fishing in a crystal-clear mountain stream.",
    "Never have I ever gone on a gondola ride in a romantic and charming city.",
    "Never have I ever gone bungee jumping.",
    "Never have I ever tried skydiving.",
    "Never have I ever gone on a solo trip to a foreign country.",
    "Never have I ever tried surfing.",
    "Never have I ever tried zip-lining.",
    "Never have I ever gone on a camping trip in the wilderness.",
    "Never have I ever tried snorkeling in the ocean.",
    "Never have I ever gone on a hike to a mountain peak.",
    "Never have I ever tried skiing.",
    "Never have I ever gone on a motorcycle road trip.",
    "Never have I ever tried white-water rafting.",
    "Never have I ever tried hang gliding.",
    "Never have I ever gone on a backpacking trip.",
    "Never have I ever gone on a snorkeling trip in the Caribbean.",
    "Never have I ever tried horseback riding on a beach.",
    "Never have I ever gone on a camping trip in the mountains.",
    "Never have I ever gone on a hot air balloon ride over a city.",
    "Never have I ever tried rock climbing on a natural rock formation.",
    "Never have I ever gone on a solo backpacking trip.",
    "Never have I ever tried surfing in Hawaii.",
    "Never have I ever tried snowboarding in the Alps.",
    "Never have I ever gone on a motorcycle road trip across a continent.",
    "Never have I ever tried paddleboarding in a tropical paradise.",
    "Never have I ever gone on a safari in South Africa.",
    "Never have I ever tried skiing in the Rocky Mountains.",
    "Never have I ever gone on a helicopter ride over a waterfall.",
    "Never have I ever tried kiteboarding in a windy destination.",
    "Never have I ever gone on a sailing trip in the Mediterranean.",
    "Never have I ever tried hang gliding over a scenic landscape.",
    "Never have I ever gone on a backpacking trip through Europe.",
    "Never have I ever tried jet skiing in the Bahamas.",
    "Never have I ever gone on a hot air balloon ride at sunset.",
    "Never have I ever tried indoor skydiving in a wind tunnel.",
    "Never have I ever gone on a snorkeling trip in Australia's Great Barrier Reef.",
    "Never have I ever tried horseback riding in the Grand Canyon.",
    "Never have I ever gone on a road trip along the Pacific Coast Highway.",
    "Never have I ever tried zip-lining in Costa Rica's rainforests.",
    "Never have I ever gone on a camping trip on a secluded island.",
    "Never have I ever tried scuba diving with sharks.",
    "Never have I ever gone on a hot air balloon ride over the Serengeti.",
    "Never have I ever tried rock climbing on a cliff by the ocean.",
    "Never have I ever gone on a solo hiking trip in the Appalachian Mountains.",
    "Never have I ever tried surfing in Australia.",
    "Never have I ever gone on a cruise to Alaska.",
    "Never have I ever tried snowboarding in Japan's powder snow.",
    "Never have I ever gone on a motorcycle road trip along Route 66.",
    "Never have I ever tried paddleboarding in the Maldives.",
    "Never have I ever gone on a safari in Kenya.",
    "Never have I ever tried skiing in the Canadian Rockies.",
    "Never have I ever gone on a helicopter ride over New York City.",
    "Never have I ever tried kiteboarding in Brazil.",
    "Never have I ever gone on a sailing trip in the Greek Islands.",
    "Never have I ever tried hang gliding in New Zealand.",
    "Never have I ever gone on a backpacking trip in Southeast Asia.",
    "Never have I ever tried jet skiing in the French Riviera.",
    "Never have I ever gone on a hot air balloon ride over the Napa Valley.",
    "Never have I ever tried indoor skydiving in Las Vegas.",
    "Never have I ever gone on a snorkeling trip in the Red Sea.",
    "Never have I ever tried horseback riding in the Scottish Highlands.",
    "Never have I ever gone on a road trip through the Australian Outback.",
    "Never have I ever tried zip-lining in the Amazon rainforest.",
    "Never have I ever gone on a camping trip in Yosemite National Park.",
    "Never have I ever tried scuba diving in the Great Blue Hole.",
    "Never have I ever gone on a hot air balloon ride over the Swiss Alps.",
    "Never have I ever tried rock climbing in Joshua Tree National Park.",
    "Never have I ever gone on a solo trekking trip in the Himalayas.",
    "Never have I ever tried surfing in Bali.",
    "Never have I ever gone on a cruise to the Galapagos Islands.",
    "Never have I ever tried snowboarding in the Andes.",
    "Never have I ever gone on a motorcycle road trip along the Great Ocean Road.",
    "Never have I ever tried paddleboarding in the Caribbean.",
    "Never have I ever gone on a safari in Tanzania.",
    "Never have I ever tried skiing in the Swiss Alps.",
    "Never have I ever gone on a helicopter ride over the Hawaiian Islands.",
    "Never have I ever tried kiteboarding in the Dominican Republic.",
    "Never have I ever gone on a sailing trip in the British Virgin Islands.",
    "Never have I ever tried hang gliding in the Swiss Alps.",
    "Never have I ever gone on a backpacking trip in South America.",
    "Never have I ever tried jet skiing in the Mediterranean Sea.",
    "Never have I ever gone on a hot air balloon ride over the Masai Mara.",
    "Never have I ever tried indoor skydiving in Dubai.",
    "Never have I ever gone on a snorkeling trip in the Maldives.",
    "Never have I ever tried horseback riding in Iceland.",
    "Never have I ever gone on a road trip along the Garden Route in South Africa.",
    "Never have I ever tried zip-lining in the Swiss Alps.",
    "Never have I ever gone on a camping trip in the Australian Outback.",
    "Never have I ever tried scuba diving in the Great Barrier Reef.",
    "Never have I ever gone on a hot air balloon ride over Cappadocia.",
    "Never have I ever tried rock climbing in Yosemite National Park.",
    "Never have I ever gone on a solo hiking trip in the Scottish Highlands.",
    "Never have I ever tried surfing in Costa Rica.",
    "Never have I ever gone on a cruise to the Norwegian fjords.",
    "Never have I ever tried snowboarding in Whistler.",
    "Never have I ever gone on a motorcycle road trip along the Pacific Coast Highway.",
    "Never have I ever tried paddleboarding in Hawaii.",
    "Never have I ever gone on a safari in Botswana.",
    "Never have I ever tried skiing in Aspen.",
    "Never have I ever gone on a helicopter ride over the Grand Canyon.",
    "Never have I ever tried kiteboarding in Cabarete.",
    "Never have I ever gone on a sailing trip in the Whitsunday Islands.",
    "Never have I ever tried hang gliding in Rio de Janeiro.",
    "Never have I ever gone on a backpacking trip in New Zealand.",
    "Never have I ever tried indoor skydiving in Orlando.",
    "Never have I ever tried horseback riding in the Rocky Mountains.",
    "Never have I ever gone on a road trip along the Ring of Kerry in Ireland.",
    "Never have I ever tried zip-lining in the Costa Rican rainforest.",
    "Never have I ever gone on a camping trip in Yellowstone National Park.",
    "Never have I ever tried scuba diving in the Maldives.",
    "Never have I ever tried rock climbing in Red River Gorge.",
    "Never have I ever gone on a solo hiking trip in the Canadian Rockies.",
    "Never have I ever tried surfing in Tofino.",
    "Never have I ever gone on a cruise to the Mediterranean.",
    "Never have I ever tried snowboarding in Lake Tahoe.",
    "Never have I ever gone on a motorcycle road trip along the Cabot Trail in Canada.",
    "Never have I ever tried paddleboarding in Bora Bora.",
    "Never have I ever gone on a safari in Zimbabwe.",
    "Never have I ever tried skiing in St. Moritz.",
    "Never have I ever gone on a helicopter ride over the Great Barrier Reef.",
    "Never have I ever tried kiteboarding in Tarifa.",
    "Never have I ever gone on a sailing trip in the Seychelles.",
    "Never have I ever tried hang gliding in Cape Town.",
    "Never have I ever gone on a backpacking trip in Patagonia.",
    "Never have I ever tried jet skiing in Miami.",
    "Never have I ever gone on a hot air balloon ride over Bagan.",
    "Never have I ever tried indoor skydiving in Sydney.",
    "Never have I ever gone on a snorkeling trip in the Galapagos Islands.",
    "Never have I ever tried horseback riding in the New Forest.",
    "Never have I ever gone on a road trip along the Amalfi Coast.",
    "Never have I ever gone on a camping trip in the Lake District.",
    "Never have I ever gone on a hot air balloon ride over the Maasai Mara.",
    "Never have I ever tried rock climbing in Kalymnos.",
    "Never have I ever gone on a solo hiking trip in the Dolomites.",
    "Never have I ever tried surfing in Jeffreys Bay.",
    "Never have I ever gone on a cruise to the South Pacific.",
    "Never have I ever tried snowboarding in the French Alps.",
    "Never have I ever gone on a motorcycle road trip along the Wild Atlantic Way.",
    "Never have I ever tried paddleboarding in Fiji.",
    "Never have I ever gone on a safari in Namibia.",
    "Never have I ever tried skiing in Vail.",
    "Never have I ever gone on a helicopter ride over the Victoria Falls.",
    "Never have I ever tried kiteboarding in Zanzibar.",
    "Never have I ever gone on a sailing trip in Croatia's Dalmatian Coast.",
    "Never have I ever tried hang gliding in the Blue Mountains.",
    "Never have I ever gone on a backpacking trip in the Inca Trail.",
    "Never have I ever tried jet skiing in the Greek Islands.",
    "Never have I ever gone on a hot air balloon ride over the Great Wall of China.",
    "Never have I ever tried indoor skydiving in Auckland.",
    "Never have I ever gone on a snorkeling trip in the Belize Barrier Reef.",
    "Never have I ever tried horseback riding in the Mongolian steppes.",
    "Never have I ever gone on a road trip along the Causeway Coastal Route in Northern Ireland.",
    "Never have I ever gone on a camping trip in Glacier National Park.",
    "Never have I ever tried scuba diving in the Komodo Islands.",
    "Never have I ever gone on a hot air balloon ride over the Atacama Desert.",
    "Never have I ever tried rock climbing in El Capitan.",
    "Never have I ever gone on a solo hiking trip in the Lake District.",
    "Never have I ever tried surfing in Hossegor.",
    "Never have I ever tried snowboarding in Niseko.",
    "Never have I ever gone on a motorcycle road trip along the Icefields Parkway.",
    "Never have I ever tried paddleboarding in the Florida Keys.",
    "Never have I ever gone on a safari in Uganda.",
    "Never have I ever tried skiing in Banff.",
    "Never have I ever gone on a helicopter ride over the Torres del Paine.",
    "Never have I ever tried kiteboarding in Cape Hatteras.",
    "Never have I ever gone on a backpacking trip in the Appalachian Trail.",
    "Never have I ever tried jet skiing in the Maldives.",
    "Never have I ever tried rock climbing on El Capitan.",
    "Never have I ever been scuba diving in a shipwreck.",
    "Never have I ever gone on a solo road trip.",
    "Never have I ever tried paragliding.",
    "Never have I ever been on a cruise to Antarctica.",
    "Never have I ever gone hiking in the Himalayas.",
    "Never have I ever gone on a camping trip in the rainforest.",
    "Never have I ever gone on a road trip without a planned destination.",
    "Never have I ever tried cave diving.",
    "Never have I ever gone on a cruise to the Arctic.",
    "Never have I ever gone on a motorcycle road trip through Europe.",
    "Never have I ever gone on a wildlife safari in the Amazon rainforest.",
    "Never have I ever gone on a camping trip in the desert.",
    "Never have I ever gone on a road trip without using GPS.",
    "Never have I ever tried cave exploration.",
    "Never have I ever gone on a solo backpacking trip in the wilderness.",
    "Never have I ever tried canyoneering.",
    "Never have I ever gone on a wildlife safari in the Serengeti.",
    "Never have I ever gone on a camping trip on a remote island.",
    "Never have I ever gone on a road trip without a map.",
    "Never have I ever tried caving in a limestone cave.",
    "Never have I ever gone on a solo hiking trip in the mountains.",
    "Never have I ever tried skydiving indoors.",
    "Never have I ever gone on a wildlife safari in the Kruger National Park.",
    "Never have I ever gone on a camping trip in the wilderness during winter.",
    "Never have I ever gone on a road trip without a specific destination.",
    "Never have I ever tried spelunking in a cave.",
    "Never have I ever gone on a solo backpacking trip in a foreign country.",
    "Never have I ever tried waterfall climbing.",
    "Never have I ever gone on a hot air balloon ride during sunrise.",
    "Never have I ever tried sandboarding on a sand dune in the Sahara Desert.",
    "Never have I ever gone on a wildlife safari in the Pantanal.",
    "Never have I ever tried snowkiting.",
    "Never have I ever gone on a road trip without a set itinerary.",
    "Never have I ever tried spelunking in an ice cave.",
    "Never have I ever gone on a solo backpacking trip in Southeast Asia.",
    "Never have I ever tried waterfall abseiling.",
    "Never have I ever gone on a cruise to the Greek Islands.",
    "Never have I ever tried sandboarding on a sand dune in Namibia.",
    "Never have I ever gone on a wildlife safari in the Maasai Mara.",
    "Never have I ever tried snowshoeing in the Rocky Mountains.",
    "Never have I ever gone on a camping trip in the Scottish Highlands.",
    "Never have I ever gone on a road trip without using a GPS or map.",
    "Never have I ever tried ice climbing in the Canadian Rockies.",
    "Never have I ever gone on a solo backpacking trip in Central America.",
    "Never have I ever tried waterfall jumping.",
    "Never have I ever tried sandboarding on a sand dune in Peru.",
    "Never have I ever gone on a wildlife safari in the Okavango Delta.",
    "Never have I ever tried snowcat skiing.",
    "Never have I ever gone on a camping trip in the Redwood Forest.",
    "Never have I ever gone on a road trip without any pre-booked accommodations.",
    "Never have I ever tried caving in a lava tube.",
    "Never have I ever gone on a solo backpacking trip in South East Asia.",
    "Never have I ever tried waterfall hiking.",
    "Never have I ever gone on a cruise to the Baltic Sea.",
    "Never have I ever tried sandboarding on a sand dune in Chile.",
    "Never have I ever tried snow biking.",
    "Never have I ever gone on a camping trip in the Canadian wilderness.",
    "Never have I ever tried flyboarding over a lake.",
    "Never have I ever gone on a road trip without a planned route.",
    "Never have I ever tried cave diving in an underwater cave.",
    "Never have I ever gone on a solo backpacking trip in the Australian Outback.",
    "Never have I ever tried waterfall rappelling in Costa Rica.",
    "Never have I ever gone on a cruise to the Alaskan fjords.",
    "Never have I ever tried sandboarding on a sand dune in Australia.",
    "Never have I ever gone on a wildlife safari in the Ngorongoro Crater.",
    "Never have I ever tried snow tubing.",
    "Never have I ever gone on a camping trip in the Swiss Alps.",
    "Never have I ever tried fly fishing in a mountain stream.",
    "Never have I ever gone on a road trip without any prior research about the destination.",
    "Never have I ever tried ice climbing in the Norwegian fjords.",
    "Never have I ever gone on a solo backpacking trip in the New Zealand wilderness.",
    "Never have I ever tried waterfall chasing.",
    "Never have I ever gone scuba diving in the Great Barrier Reef.",
    "Never have I ever tried skydiving from a plane.",
    "Never have I ever been on a solo trip to a foreign country.",
    "Never have I ever tried zip-lining through a rainforest canopy.",
    "Never have I ever tried rock climbing on a natural cliff.",
    "Never have I ever tried whitewater rafting in a turbulent river.",
    "Never have I ever been on a solo backpacking trip in the mountains.",
    "Never have I ever tried snorkeling in the Maldives.",
    "Never have I ever tried skiing or snowboarding in the Alps.",
    "Never have I ever gone on a solo road trip across a continent.",
    "Never have I ever tried parasailing over the ocean.",
    "Never have I ever tried kayaking in a bioluminescent bay.",
    "Never have I ever tried skydiving indoors in a wind tunnel.",
    "Never have I ever tried canyoneering in a slot canyon.",
    "Never have I ever gone on a solo backpacking trip in Europe.",
    "Never have I ever tried paddleboarding in a serene lake.",
    "Never have I ever tried snowshoeing in the mountains.",
    "Never have I ever gone on a camping trip in the national parks of the United States.",
    "Never have I ever tried flyboarding on a crystal-clear lake.",
    "Never have I ever gone on a road trip without a map or GPS.",
    "Never have I ever tried snorkeling in the Great Barrier Reef.",
    "Never have I ever gone on a solo backpacking trip in South America.",
    "Never have I ever gone on a wildlife safari in the Masai Mara.",
    "Never have I ever tried skiing or snowboarding in the Rocky Mountains.",
    "Never have I ever tried kiteboarding on a tropical beach.",
    "Never have I ever gone on a road trip without any prior accommodations booked.",
    "Never have I ever tried ice climbing in a glacier.",
]

export function get_never_have_i_ever() {
    let randomNumber = Math.floor(Math.random() * nhie.length);
    let randomQuestion = nhie[randomNumber];
    return(randomQuestion);
}