export let questions = [ 
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather have a photographic memory or the ability to forget anything you want?",
    "Would you rather be able to speak all languages fluently or be a master of every musical instrument?",
    "Would you rather live in a world without technology or a world without art?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather be able to teleport anywhere or read minds?",
    "Would you rather have the power to control fire or water?",
    "Would you rather be able to speak to animals or speak all human languages?",
    "Would you rather have the ability to time travel or see into the future?",
    "Would you rather live without music or without television?",
    "Would you rather always have to sing instead of speaking or dance everywhere you go?",
    "Would you rather be able to change the past or control the future?",
    "Would you rather be able to run at superhuman speed or have incredible strength?",
    "Would you rather live in a world with no internet or no air conditioning and heating?",
    "Would you rather be a famous actor or a renowned scientist?",
    "Would you rather always have to tell the truth or never be able to speak again?",
    "Would you rather spend a year traveling the world or a year living in one place you've always wanted to visit?",
    "Would you rather have the ability to teleport anywhere or be able to breathe underwater?",
    "Would you rather be able to control your dreams or never have to sleep?",
    "Would you rather have the power to heal any illness or the power to bring people back to life?",
    "Would you rather have unlimited wealth or unlimited wisdom?",
    "Would you rather always have bad breath or always have body odor?",
    "Would you rather live in a world without books or a world without movies?",
    "Would you rather be able to communicate with animals or speak all foreign languages fluently?",
    "Would you rather have the ability to stop time or rewind time?",
    "Would you rather never be able to use social media again or never be able to watch another movie or TV show?",
    "Would you rather have the power to control the weather or have the ability to teleport?",
    "Would you rather have a personal chef or a personal trainer?",
    "Would you rather have the ability to read minds or be able to see the future?",
    "Would you rather always have to wear a clown wig in public or always have to wear a nose and clown shoes?",
    "Would you rather be able to breathe underwater or have the ability to see in the dark?",
    "Would you rather be a famous musician or a famous athlete?",
    "Would you rather have the power of invisibility or the power of super strength?",
    "Would you rather be able to talk to animals or speak every human language fluently?",
    "Would you rather never have to sleep or never have to eat?",
    "Would you rather live without your smartphone or without your car?",
    "Would you rather have the ability to control minds or have the ability to control time?",
    "Would you rather have the power to cure any disease or end world hunger?",
    "Would you rather have the ability to fly or be able to breathe underwater?",
    "Would you rather live in a world with no music or a world with no movies?",
    "Would you rather have the ability to teleport anywhere or have the ability to read minds?",
    "Would you rather have the power to control fire or have the power to control water?",
    "Would you rather be able to speak every language fluently or have perfect musical pitch?",
    "Would you rather have the ability to see one year into the future or be able to change one event from the past?",
    "Would you rather live without the internet or without air conditioning and heating?",
    "Would you rather be a famous actor or a successful entrepreneur?",
    "Would you rather always have to speak in rhyme or have to sing instead of speaking?",
    "Would you rather be able to control your dreams or have the ability to never need sleep?",
    "Would you rather have the power to heal any injury or have the power to bring back extinct species?",
    "Would you rather have unlimited wealth or unlimited knowledge?",
    "Would you rather have the ability to teleport anywhere instantly or have the power to time travel?",
    "Would you rather have the power to control the weather or control people's emotions?",
    "Would you rather be able to speak every language fluently or be a master of all forms of art?",
    "Would you rather live in a world without music or a world without books?",
    "Would you rather have the ability to speak to animals or have the power to understand and manipulate technology?",
    "Would you rather have the power to control gravity or control probability?",
    "Would you rather be able to transform into any animal at will or be able to communicate with plants?",
    "Would you rather have the ability to change your appearance at any time or have the power to read minds?",
    "Would you rather have the ability to control dreams or have the power to control nightmares?",
    "Would you rather have the power of telekinesis or the power of telepathy?",
    "Would you rather live in a world without sadness or a world without anger?",
    "Would you rather have the ability to speak and understand all fictional languages or be able to visit any fictional world?",
    "Would you rather have the power to freeze time or have the power to rewind time?",
    "Would you rather be able to communicate with the deceased or have the ability to predict the future accurately?",
    "Would you rather be able to breathe underwater or have the power to fly like a bird?",
    "Would you rather have the ability to control and manipulate fire or have the power to control and manipulate electricity?",
    "Would you rather have the power to instantly learn and master any skill or have the power to heal any physical or emotional pain?",
    "Would you rather have the ability to erase your own memories or erase others' memories?",
    "Would you rather have the power to bring inanimate objects to life or bring fictional characters into reality?",
    "Would you rather have the power to control and manipulate plants or have the power to control and manipulate the elements (earth, air, fire, water)?",
    "Would you rather live in a world without laughter or a world without love?",
    "Would you rather have the ability to understand and speak to insects or have the power to control the weather?",
    "Would you rather have the power to instantly learn and understand any new concept or have the power to speak and understand all languages, including those from alien civilizations?",
    "Would you rather be able to communicate with extraterrestrial beings or travel to any planet in the universe?",
    "Would you rather have the power to control and manipulate dreams or have the power to bring dreams into reality?",
    "Would you rather have the ability to see one minute into the future or have the power to travel one hour into the past?",
    "Would you rather have the power to make anyone fall in love with you or have the power to make anyone forget about you completely?",
    "Would you rather have the power to control and manipulate sound or have the power to control and manipulate light?",
    "Would you rather have the ability to talk to mythical creatures or have the power to summon them at will?",
    "Would you rather have the power to communicate with aliens or have the ability to understand and interpret ancient languages?",
    "Would you rather be able to control and manipulate your dreams or have the power to create new universes?",
    "Would you rather have the power to make yourself invisible or have the power to clone yourself?",
    "Would you rather have the ability to stop time for one hour every day or have the power to reverse aging?",
    "Would you rather have the power to control and manipulate luck or have the power to control and manipulate dreams?",
    "Would you rather have the ability to speak and understand animals' thoughts or have the power to control and manipulate the weather?",
    "Would you rather have the power to make any two people fall in love or have the power to end any conflict peacefully?",
    "Would you rather have the ability to transform into any mythical creature at will or have the power to control and manipulate the elements (earth, air, fire, water)?",
    "Would you rather have the power to cure any disease or have the power to prevent any natural disaster?",
    "Would you rather be able to speak and understand any dead language or have the power to communicate with spirits?",
    "Would you rather have the power to control and manipulate time or have the power to control and manipulate space?",
    "Would you rather have the ability to bring inanimate objects to life or have the power to bring deceased loved ones back to life temporarily?",
    "Would you rather have the power to control and manipulate thoughts or have the power to control and manipulate emotions?",
    "Would you rather have the ability to control and manipulate electricity or have the power to control and manipulate gravity?",
    "Would you rather have the power to instantly heal any physical injury or have the power to instantly heal any emotional pain?",
    "Would you rather have the ability to understand and interpret dreams or have the power to enter other people's dreams?",
    "Would you rather have the power to communicate with animals or have the power to communicate with aliens?",
    "Would you rather have the ability to see through walls or have the power to become invisible at will?",
    "Would you rather have the power to change the outcome of historical events or have the power to shape the future of humanity?",
    "Would you rather be able to control and manipulate your own dreams or have the power to control and manipulate the dreams of others?",
    "Would you rather have the power to control and manipulate the minds of others or have the power to control and manipulate the physical world around you?",
    "Would you rather have the ability to speak every language fluently or be a master of every musical instrument?",
    "Would you rather have the power to control gravity or control time?",
    "Would you rather be able to fly or have the ability to turn invisible?",
    "Would you rather have the ability to speak to animals or speak all human languages fluently?",
    "Would you rather have the power to see into the future or change the past?",
    "Would you rather have the ability to breathe underwater or have the power to communicate with marine life?",
    "Would you rather have the power of super strength or the power of super speed?",
    "Would you rather always have to tell the truth or always lie?",
    "Would you rather have the ability to heal any illness or have the power to bring people back to life?",
    "Would you rather have the power to control minds or have the power to control weather?",
    "Would you rather have the ability to stop time or have the ability to manipulate dreams?",
    "Would you rather have the power to control and manipulate plants or have the power to control and manipulate animals?",
    "Would you rather be able to speak and understand all languages or be able to play any instrument with perfection?",
    "Would you rather have the power to travel to any place in the world or have the power to teleport to any point in time?",
    "Would you rather have the ability to read minds or have the ability to see the future?",
    "Would you rather be able to control and manipulate electricity or have the power to control and manipulate weather?",
    "Would you rather have the power to bring good luck to yourself or have the power to bring bad luck to others?",
    "Would you rather have the ability to shapeshift into any animal or have the ability to clone yourself?",
    "Would you rather have the power to become invisible or have the power to control people's emotions?",
    "Would you rather have the ability to speak to the dead or have the ability to see ghosts?",
    "Would you rather be able to communicate with extraterrestrial beings or be able to understand all ancient languages?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate nightmares?",
    "Would you rather have the ability to control and manipulate time or have the ability to control and manipulate space?",
    "Would you rather have the ability to understand and speak to insects or have the power to control and manipulate the weather?",
    "Would you rather have the power to control and manipulate your own dreams or have the power to control and manipulate other people's dreams?",
    "Would you rather have the ability to communicate with animals or have the ability to communicate with plants?",
    "Would you rather have the power to control and manipulate fire or have the power to control and manipulate ice?",
    "Would you rather have the ability to understand and interpret dreams or have the power to control and manipulate thoughts?",
    "Would you rather have the ability to control and manipulate electricity or have the power to control and manipulate magnetism?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate reality?",
    "Would you rather have the ability to speak and understand all dead languages or have the power to communicate with spirits?",
    "Would you rather have the power to control and manipulate emotions or have the power to control and manipulate weather?",
    "Would you rather have the ability to communicate with extraterrestrial beings or have the power to travel to any planet in the universe?",
    "Would you rather have the power to control and manipulate your own dreams or have the power to control and manipulate time?",
    "Would you rather have the ability to control and manipulate dreams or have the power to control and manipulate thoughts?",
    "Would you rather have the power to control and manipulate fire or have the power to control and manipulate earth?",
    "Would you rather have the ability to speak and understand any fictional language or have the power to visit any fictional world?",
    "Would you rather have the power to control and manipulate weather or have the power to control and manipulate energy?",
    "Would you rather have the ability to teleport anywhere instantly or have the power to communicate with animals?",
    "Would you rather have the ability to understand and interpret dreams or have the power to control and manipulate luck?",
    "Would you rather have the power to control and manipulate your own dreams or have the power to control and manipulate reality?",
    "Would you rather have the ability to communicate with animals or have the power to communicate with plants?",
    "Would you rather have the ability to control and manipulate thoughts or have the power to control and manipulate emotions?",
    "Would you rather have the ability to control and manipulate gravity or have the power to control and manipulate light?",
    "Would you rather have the power to read minds or have the power to predict the future?",
    "Would you rather have the ability to speak and understand any animal language or have the power to heal any physical injury?",
    "Would you rather live in a world where everyone can fly or a world where everyone has super strength?",
    "Would you rather have the power to control and manipulate technology or have the power to control and manipulate nature?",
    "Would you rather have the ability to teleport anywhere in the world or have the power to time travel?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate emotions?",
    "Would you rather be a famous celebrity for a day or have a lifetime of privacy and anonymity?",
    "Would you rather have the ability to speak and understand all human languages or have the power to instantly learn any skill?",
    "Would you rather have the power to control and manipulate fire or have the power to control and manipulate water?",
    "Would you rather have the ability to see one year into the future or have the power to erase one day from your past?",
    "Would you rather live in a world where everyone tells the truth or a world where everyone is always kind?",
    "Would you rather have the power to control and manipulate sound or have the power to control and manipulate thoughts?",
    "Would you rather have the ability to change your appearance at will or have the power to change someone else's appearance?",
    "Would you rather have the power to control and manipulate weather or have the power to control and manipulate luck?",
    "Would you rather be able to communicate with plants or have the power to communicate with the dead?",
    "Would you rather have the ability to travel to any place in the world instantly or have the power to instantly heal any illness?",
    "Would you rather have the ability to understand and interpret dreams or have the power to control and manipulate gravity?",
    "Would you rather have the power to control and manipulate emotions or have the power to control and manipulate thoughts?",
    "Would you rather be able to teleport anywhere instantly or have the power to communicate with animals?",
    "Would you rather have the ability to speak and understand any language fluently or have the power to communicate with animals?",
    "Would you rather be able to fly like a bird or swim like a fish?",
    "Would you rather have the ability to teleport to any place on Earth or be able to teleport to any place in space?",
    "Would you rather have the power to become invisible at will or have the ability to read minds?",
    "Would you rather have the ability to time travel to the past or travel to the future?",
    "Would you rather be able to speak and understand every musical instrument or be able to speak and understand every human language?",
    "Would you rather have the power to control and manipulate plants or have the power to control and manipulate the weather?",
    "Would you rather have the ability to live without sleep or live without eating?",
    "Would you rather have the power to control and manipulate electricity or have the power to control and manipulate magnetism?",
    "Would you rather be able to change your physical appearance at will or have the power to change your age?",
    "Would you rather have the ability to breathe underwater or have the ability to withstand extreme temperatures?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate thoughts?",
    "Would you rather have the ability to speak and understand any animal language or have the power to communicate with the deceased?",
    "Would you rather have the power to control and manipulate gravity or have the power to control and manipulate time?",
    "Would you rather have the ability to instantly learn and master any skill or have the power to heal any physical or mental ailment?",
    "Would you rather have the ability to turn invisible or have the ability to teleport?",
    "Would you rather have the power to control and manipulate your own emotions or have the power to control and manipulate the emotions of others?",
    "Would you rather be able to communicate with extraterrestrial beings or be able to communicate with mythical creatures?",
    "Would you rather have the ability to transform into any animal at will or have the ability to speak and understand all human languages?",
    "Would you rather have the power to control and manipulate the elements (fire, water, earth, air) or have the power to control and manipulate time?",
    "Would you rather have the ability to remember everything you read or have the ability to remember everything you hear?",
    "Would you rather be able to control and manipulate the minds of others or have the power to control and manipulate the physical world?",
    "Would you rather have the ability to travel to any point in history or have the ability to see into the future?",
    "Would you rather have the power to control and manipulate the weather or have the power to control and manipulate luck?",
    "Would you rather have the ability to communicate with animals or have the power to heal any illness or injury?",
    "Would you rather have the power to fly or the power to become invisible?",
    "Would you rather have the ability to teleport anywhere instantly or the ability to read minds?",
    "Would you rather have the power to control fire or the power to control water?",
    "Would you rather have the ability to speak and understand all languages or the ability to play any musical instrument?",
    "Would you rather be able to communicate with animals or be able to communicate with plants?",
    "Would you rather have the power to time travel to the past or the power to see into the future?",
    "Would you rather have the ability to breathe underwater or the ability to survive in extreme temperatures?",
    "Would you rather have the power to control and manipulate weather or the power to control and manipulate emotions?",
    "Would you rather have the ability to change your physical appearance at will or the ability to heal others?",
    "Would you rather be able to control and manipulate dreams or be able to control and manipulate reality?",
    "Would you rather have the power to control and manipulate electricity or the power to control and manipulate magnetism?",
    "Would you rather have the ability to speak and understand any animal language or the ability to speak and understand any human language?",
    "Would you rather have the power to control and manipulate thoughts or the power to control and manipulate dreams?",
    "Would you rather have the ability to communicate with extraterrestrial beings or the ability to communicate with spirits?",
    "Would you rather have the power to control and manipulate gravity or the power to control and manipulate time?",
    "Would you rather have the ability to instantly learn and master any skill or the ability to heal any physical or mental ailment?",
    "Would you rather have the power to control and manipulate sound or the power to control and manipulate light?",
    "Would you rather have the ability to turn invisible or the ability to teleport?",
    "Would you rather have the power to control and manipulate your own emotions or the power to control and manipulate the emotions of others?",
    "Would you rather have the ability to transform into any animal at will or the ability to speak and understand all human languages?",
    "Would you rather have the power to control and manipulate the elements (fire, water, earth, air) or the power to control and manipulate time?",
    "Would you rather have the ability to remember everything you read or the ability to remember everything you hear?",
    "Would you rather have the power to control and manipulate dreams or the power to control and manipulate reality?",
    "Would you rather have the ability to travel to any point in history or the ability to see into the future?",
    "Would you rather have the power to control and manipulate the weather or the power to control and manipulate luck?",
    "Would you rather have the ability to communicate with animals or the ability to heal any illness or injury?",
    "Would you rather have the power to control and manipulate fire or the power to control and manipulate ice?",
    "Would you rather have the ability to speak and understand any fictional language or the ability to visit any fictional world?",
    "Would you rather have the power to control and manipulate weather or the power to control and manipulate energy?",
    "Would you rather have the ability to teleport anywhere instantly or the ability to communicate with animals?",
    "Would you rather have the power to control and manipulate time or the power to control and manipulate space?",
    "Would you rather have the ability to understand and interpret dreams or the ability to control and manipulate luck?",
    "Would you rather have the power to control and manipulate your own dreams or the power to control and manipulate reality?",
    "Would you rather have the ability to communicate with animals or the ability to communicate with plants?",
    "Would you rather have the ability to control and manipulate thoughts or the ability to control and manipulate emotions?",
    "Would you rather have the power to make anyone fall in love with you or the power to make anyone forget about you completely?",
    "Would you rather have the ability to control and manipulate electricity or the ability to control and manipulate magnetism?",
    "Would you rather have the ability to speak and understand all dead languages or the ability to communicate with spirits?",
    "Would you rather have the power to control and manipulate emotions or the power to control and manipulate weather?",
    "Would you rather have the ability to communicate with extraterrestrial beings or the ability to travel to any planet in the universe?",
    "Would you rather have the power to control and manipulate your own dreams or the power to control and manipulate time?",
    "Would you rather have the ability to control and manipulate dreams or the ability to control and manipulate thoughts?",
    "Would you rather have the power to control and manipulate fire or the power to control and manipulate earth?",
    "Would you rather have the ability to read minds or the ability to see the future?",
    "Would you rather be able to speak all languages fluently or play all musical instruments flawlessly?",
    "Would you rather have the power of invisibility or the power of flight?",
    "Would you rather have the ability to time travel to the past or to the future?",
    "Would you rather live in a world with no technology or in a world with no nature?",
    "Would you rather be able to teleport anywhere instantly or be able to clone yourself?",
    "Would you rather have the power to heal any illness or injury or have the power to bring the dead back to life?",
    "Would you rather be a famous celebrity or a respected leader?",
    "Would you rather have the ability to stop time or the ability to rewind time?",
    "Would you rather live in a world with no pain or a world with no fear?",
    "Would you rather have the ability to travel to any point in history or the ability to travel to any point in the future?",
    "Would you rather have the power to control and manipulate minds or the power to control and manipulate matter?",
    "Would you rather have the ability to speak and understand all languages or have the ability to solve any mathematical problem instantly?",
    "Would you rather be able to change your physical appearance at will or be able to change your personality at will?",
    "Would you rather have the ability to fly like a bird or swim like a fish?",
    "Would you rather have the power to make others tell the truth or the power to make others fall in love with you?",
    "Would you rather have the ability to remember everything or the ability to forget anything?",
    "Would you rather have the power to control and manipulate dreams or the power to control and manipulate thoughts?",
    "Would you rather have the ability to communicate with extraterrestrial beings or have the ability to visit other planets?",
    "Would you rather have the ability to turn invisible or the ability to create illusions?",
    "Would you rather be able to control and manipulate the weather or have the power to control and manipulate luck?",
    "Would you rather have the ability to communicate with animals or have the ability to understand and speak all programming languages?",
    "Would you rather have the ability to visit any place in the world instantly or have the ability to communicate with any historical figure?",
    "Would you rather be able to communicate with animals or have the power to heal any physical or mental ailment?",
    "Would you rather have the ability to control and manipulate the elements (fire, water, earth, air) or have the ability to control and manipulate technology?",
    "Would you rather have the ability to understand and interpret dreams or have the ability to control and manipulate luck?",
    "Would you rather be able to speak and understand all known human languages or have the ability to speak and understand the languages of all animals?",
    "Would you rather have the ability to communicate with extraterrestrial beings or have the ability to time travel to any point in history?",
    "Would you rather be able to teleport anywhere instantly or have the power to shape-shift into any animal?",
    "Would you rather have the ability to control and manipulate dreams or have the ability to control and manipulate thoughts?",
    "Would you rather be able to understand and interpret any ancient language or have the ability to predict the outcome of any event accurately?",
    "Would you rather be able to communicate with plants or have the power to control and manipulate the weather?",
    "Would you rather have the ability to speak and understand all fictional languages or have the ability to travel to any fictional world?",
    "Would you rather be able to control and manipulate electricity or have the power to control and manipulate magnetism?",
    "Would you rather have the ability to communicate with animals or have the ability to communicate with the spirits of the deceased?",
    "Would you rather be able to teleport anywhere instantly or have the power to control and manipulate time?",
    "Would you rather have the power to control and manipulate your own dreams or have the power to control and manipulate thoughts?",
    "Would you rather be able to speak and understand all languages fluently or have the ability to play any musical instrument beautifully?",
    "Would you rather have the ability to control and manipulate fire or have the power to control and manipulate water?",
    "Would you rather have the power to heal any physical injury or have the power to heal any emotional trauma?",
    "Would you rather be able to fly like a bird or have the ability to breathe underwater like a fish?",
    "Would you rather have the ability to time travel to any point in history or have the ability to see into the future?",
    "Would you rather be able to communicate with animals or have the ability to communicate with plants?",
    "Would you rather have the power to control and manipulate weather or have the power to control and manipulate emotions?",
    "Would you rather live in a world where everyone has superpowers or in a world where no one has superpowers?",
    "Would you rather have the ability to speak and understand all known human languages or have the ability to speak and understand the languages of all extraterrestrial beings?",
    "Would you rather be able to control and manipulate the elements (fire, water, earth, air) or have the ability to control and manipulate technology?",
    "Would you rather have the ability to communicate with animals or have the ability to communicate with ghosts and spirits?",
    "Would you rather have the ability to fly or have the ability to become invisible?",
    "Would you rather live in a world with no internet or live in a world with no cell phones?",
    "Would you rather be a famous actor or a famous musician?",
    "Would you rather be able to read minds or be able to see the future?",
    "Would you rather have a photographic memory or have the ability to forget anything you want?",
    "Would you rather live without music or live without television?",
    "Would you rather have the ability to speak all languages fluently or have the ability to play any musical instrument?",
    "Would you rather always have to tell the truth or always have to lie?",
    "Would you rather have the power to heal others or have the power to bring the dead back to life?",
    "Would you rather have the ability to teleport anywhere or have the ability to time travel?",
    "Would you rather be able to breathe underwater or be able to explore outer space?",
    "Would you rather have the power to control the weather or have the power to control animals?",
    "Would you rather have unlimited money or unlimited knowledge?",
    "Would you rather be able to speak with animals or be able to speak all human languages?",
    "Would you rather have the ability to be invisible or have the ability to walk through walls?",
    "Would you rather live in a world with superheroes or live in a world with magic?",
    "Would you rather be a famous athlete or a famous scientist?",
    "Would you rather have the power to control time or have the power to control minds?",
    "Would you rather live without music or live without movies?",
    "Would you rather have the ability to travel to any place in the world instantly or have the ability to teleport to any point in history?",
    "Would you rather have the power to control and manipulate plants or have the power to control and manipulate technology?",
    "Would you rather have the ability to speak to the dead or have the ability to see into the future?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate luck?",
    "Would you rather be able to fly at super speed or have super strength?",
    "Would you rather have the ability to stop time or have the ability to rewind time?",
    "Would you rather live in a world with no electricity or live in a world with no transportation?",
    "Would you rather have the ability to talk to animals or have the ability to talk to objects?",
    "Would you rather be able to change the past or be able to see the future?",
    "Would you rather live without books or live without movies?",
    "Would you rather have the ability to control and manipulate weather or have the ability to control and manipulate time?",
    "Would you rather have the power to heal any physical ailment or have the power to heal any mental illness?",
    "Would you rather have the ability to speak every language fluently or have the ability to play every musical instrument perfectly?",
    "Would you rather have the ability to become invisible or have the ability to read minds?",
    "Would you rather live in a world with only black and white or live in a world with no sound?",
    "Would you rather have the power to control and manipulate water or have the power to control and manipulate earth?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to communicate with animals?",
    "Would you rather be a famous writer or a famous painter?",
    "Would you rather have the power to control and manipulate your own dreams or have the power to control and manipulate the dreams of others?",
    "Would you rather have the ability to speak any language fluently or have the ability to play any sport professionally?",
    "Would you rather have the power to control and manipulate fire or have the power to control and manipulate wind?",
    "Would you rather live in a world without books or live in a world without movies?",
    "Would you rather have the ability to time travel to the past or have the ability to see into the future?",
    "Would you rather be able to communicate with animals or be able to communicate with aliens?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to fly like a bird?",
    "Would you rather have the ability to control and manipulate water or have the ability to control and manipulate electricity?",
    "Would you rather be a famous actor or a famous athlete?",
    "Would you rather have the power to control and manipulate time or have the power to control and manipulate minds?",
    "Would you rather live in a world without internet or live in a world without air conditioning?",
    "Would you rather have the ability to speak and understand all human languages or have the ability to speak and understand all computer languages?",
    "Would you rather be able to see in the dark or be able to see through walls?",
    "Would you rather have the ability to control and manipulate dreams or have the ability to control and manipulate luck?",
    "Would you rather be a famous writer or a famous musician?",
    "Would you rather be a famous actor or a famous scientist?",
    "Would you rather be able to fly or be able to breathe underwater?",
    "Would you rather have the ability to read minds or have the ability to teleport?",
    "Would you rather live in a world without technology or live in a world without art?",
    "Would you rather have the power to be invisible or have the power to be invincible?",
    "Would you rather never have to sleep again or never have to eat again?",
    "Would you rather have the ability to speak all languages fluently or have the ability to play every musical instrument perfectly?",
    "Would you rather live in a house made entirely of glass or live in a house without windows?",
    "Would you rather have the power to control fire or have the power to control ice?",
    "Would you rather have the ability to time travel to the past and change one event or have the ability to see your future?",
    "Would you rather have the power to heal any illness or have the power to bring back the dead?",
    "Would you rather be able to talk to animals or be able to speak any human language?",
    "Would you rather be famous for your intelligence or famous for your beauty?",
    "Would you rather have the ability to control the weather or have the ability to control probability?",
    "Would you rather have the power to control plants or have the power to control animals?",
    "Would you rather be able to see 10 minutes into the future or be able to see 100 years into the future?",
    "Would you rather have the ability to control your dreams or have the ability to control your nightmares?",
    "Would you rather have the power to teleport to any place on Earth or have the power to teleport to any planet in the universe?",
    "Would you rather have the ability to understand and speak every animal language or have the ability to communicate with extraterrestrial beings?",
    "Would you rather have the power to control gravity or have the power to control time?",
    "Would you rather live in a world without music or live in a world without books?",
    "Would you rather have the ability to change your appearance at will or have the ability to change the appearance of others?",
    "Would you rather have the power to stop time for one hour every day or have the power to rewind time by one day once a month?",
    "Would you rather be able to talk to the deceased or be able to see into the future?",
    "Would you rather have the ability to control your dreams or have the ability to control your emotions?",
    "Would you rather live in a world without colors or live in a world without music?",
    "Would you rather have the power to control the minds of others or have the power to control the elements?",
    "Would you rather be able to speak and understand all human languages or be able to communicate with machines?",
    "Would you rather have the ability to transform into any animal or have the ability to transform into any inanimate object?",
    "Would you rather have the power to heal any physical injury or have the power to heal any emotional pain?",
    "Would you rather have the ability to fly at the speed of light or have the ability to travel through time?",
    "Would you rather have the power to control technology with your mind or have the power to control the weather with your mind?",
    "Would you rather always have to wear a costume in public or always have to speak in rhyme?",
    "Would you rather have the ability to see through walls or have the ability to turn invisible?",
    "Would you rather be able to speak and understand every language in the world or be able to communicate with animals?",
    "Would you rather have the ability to teleport to any place instantly or have the ability to teleport others?",
    "Would you rather have the power to control people's emotions or have the power to control people's thoughts?",
    "Would you rather have the ability to change the past or have the ability to predict the future?",
    "Would you rather have the power to control the minds of others or have the power to control the weather?",
    "Would you rather have the ability to talk to plants or have the ability to talk to ghosts?",
    "Would you rather be able to see in complete darkness or be able to see miles away like a hawk?",
    "Would you rather have the power to bring peace to the world or have the power to end hunger?",
    "Would you rather have the ability to understand any scientific concept or have the ability to solve any mathematical problem?",
    "Would you rather have the ability to speak and understand every human language or have the ability to speak and understand every programming language?",
    "Would you rather have the power to control fire or have the power to control earth?",
    "Would you rather have the ability to communicate with animals or have the ability to communicate with the dead?",
    "Would you rather be able to teleport anywhere in the world instantly or be able to time travel to any point in history?",
    "Would you rather have the ability to control and manipulate dreams or have the ability to control and manipulate memories?",
    "Would you rather have the power to control electricity or have the power to control magnetism?",
    "Would you rather live in a world without music or live in a world without art?",
    "Would you rather have the ability to speak and understand all animal languages or have the ability to speak and understand all alien languages?",
    "Would you rather have the power to control weather patterns or have the power to control natural disasters?",
    "Would you rather be able to see into the future but not be able to change it or be able to change the past but not be able to see the future?",
    "Would you rather have the ability to control and manipulate technology or have the ability to control and manipulate nature?",
    "Would you rather have the power to control your own dreams or have the power to control other people's dreams?",
    "Would you rather have the ability to teleport to any place instantly or have the ability to teleport objects?",
    "Would you rather have the ability to see in complete darkness or have the ability to see through objects?",
    "Would you rather have the power to control minds or have the power to control emotions?",
    "Would you rather have the ability to fly or have the ability to breathe underwater?",
    "Would you rather have the power to change your appearance at will or have the power to read minds?",
    "Would you rather have the ability to teleport anywhere in the world instantly or have the ability to time travel to any point in history?",
    "Would you rather have the power to control and manipulate dreams or have the power to control and manipulate memories?",
    "Would you rather have the ability to control electricity or have the ability to control magnetism?",
    "Would you rather be able to speak and understand all human languages or be able to speak and understand all animal languages?",
    "Would you rather have the ability to control fire or have the ability to control wind?",
    "Would you rather have the power to control your dreams or have the power to control reality?",
    "Would you rather live in a world without music or live in a world without movies?",
    "Would you rather have the ability to teleport to any place instantly or have the ability to time travel to any point in history?",
    "Would you rather have the power to control water or have the power to control earth?",
    "Would you rather be able to see through walls or have the ability to become invisible?",
    "Would you rather have the ability to control and manipulate dreams or have the ability to control and manipulate emotions?",
    "Would you rather live without internet or live without air conditioning?",
    "Would you rather have the power to control fire or have the power to control electricity?",
    "Would you rather be able to see in the dark or be able to see into the future?",
    "Would you rather have the power to control your own dreams or have the power to control thoughts?",
    "Would you rather have the power to control weather or have the power to control emotions?",
    "Would you rather always have to speak your mind or never be able to speak again?",
    "Would you rather be able to read minds or have the power to control minds?",
    "Would you rather be stranded on a deserted island alone or be stranded with someone you dislike?",
    "Would you rather have unlimited money but live for only 10 more years or have a moderate amount of money and live for 50 more years?",
    "Would you rather have the power to time travel but never be able to change anything or have the power to change the past but not be able to time travel?",
    "Would you rather always have to wear formal attire or always have to wear pajamas?",
    "Would you rather have the ability to breathe underwater or have the ability to walk on walls and ceilings?",
    "Would you rather live in a world with no technology or live in a world with no books?",
    "Would you rather have the ability to speak to animals or have the ability to speak to plants?",
    "Would you rather be able to teleport anywhere instantly or be able to transform into any animal at will?",
    "Would you rather have the power to heal any illness or have the power to bring the dead back to life?",
    "Would you rather have the ability to control the weather or have the ability to control luck?",
    "Would you rather be able to remember everything you see or be able to remember everything you hear?",
    "Would you rather have the power to control your dreams or have the power to control your nightmares?",
    "Would you rather have the ability to become invisible or have the ability to see through walls?",
    "Would you rather have a photographic memory or have an IQ of 200?",
    "Would you rather be able to speak all languages fluently or be able to play all musical instruments?",
    "Would you rather have the power to control minds or have the power to control time?",
    "Would you rather have the ability to control and manipulate gravity or have the ability to control and manipulate magnetism?",
    "Would you rather be able to talk to animals or be able to speak all human languages?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to fly at super speed?",
    "Would you rather have the power to heal any illness or have the power to bring peace to the world?",
    "Would you rather live in a world with no music or live in a world with no movies?",
    "Would you rather have the ability to see the future or have the ability to change the past?",
    "Would you rather be able to speak every language fluently or be able to communicate with animals?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to be invisible whenever you want?",
    "Would you rather have the power to control and manipulate minds or have the power to control and manipulate matter?",
    "Would you rather have the power to control and manipulate electricity or have the power to control and manipulate gravity?",
    "Would you rather be able to talk to animals or be able to understand all languages spoken by humans?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to time travel to any point in history?",
    "Would you rather have the power to heal any illness or have the power to resurrect the dead?",
    "Would you rather be able to speak every language fluently or be able to play every musical instrument perfectly?",
    "Would you rather have the ability to communicate with animals or have the ability to speak every language fluently?",
    "Would you rather have the ability to teleport anywhere instantly or have the ability to read minds?",
    "Would you rather have the ability to control and manipulate dreams or have the ability to control and manipulate gravity?",
    "Would you rather be able to see into the future or have the ability to change the past?",
    "Would you rather have the power to control and manipulate water or have the power to control and manipulate electricity?",
    "Would you rather have the ability to control and manipulate water or have the ability to control and manipulate air?",
    "Would you rather be able to speak and understand all human languages or have the ability to speak and understand all animal languages?",
    "Would you rather live in a world with no internet or a world with no television?",
    "Would you rather be able to teleport anywhere or be able to read minds?",
    "Would you rather have the ability to speak all languages fluently or play all musical instruments perfectly?",
    "Would you rather have the power to control fire or control water?",
    "Would you rather have the ability to see one year into the future or be able to change one event from your past?",
    "Would you rather be able to communicate with animals or speak all human languages fluently?",
    "Would you rather be able to control the weather or control time?",
    "Would you rather have the ability to become invisible or be able to fly?",
    "Would you rather have the ability to see in the dark or have the ability to see through walls?",
    "Would you rather eat a bug or a fly?",
    "Would you rather lick the floor or a broom?",
    "Would you rather eat ice cream or cake?",
    "Would you rather lick your keyboard or mouse?",
    "Would you rather wash your hair with mash potatoes or cranberry sauce?",
    "Would you rather team up with Wonder Woman or Captain Marvel?",
    "Would you rather want to find true love or win lottery next month?",
    "Would you rather be forced to sing along or dance to every song you hear?",
    "Would you rather have everyone you know be able to read your thoughts or for everyone you know to have access to your Internet history?",
    "Would you rather be chronically under-dressed or overdressed?",
    "Would you rather clean a toliet or a babys diaper",
    "Would you rather lose your sight or your memories?",
    "Would you rather have universal respect or unlimited power?",
    "Would you rather give up air conditioning and heating for the rest of your life or give up the Internet for the rest of your life?",
    "Would you rather swim in a pool full of Nutella or a pool full of maple syrup?",
    "Would you rather labor under a hot sun or extreme cold?",
    "Would you rather stay in during a snow day or build a fort?",
    "Would you rather buy 10 things you don't need every time you go shopping or always forget the one thing that you need when you go to the store?",
    "Would you rather never be able to go out during the day or never be able to go out at night?",
    "Would you rather have a personal maid or a personal chef?",
    "Would you rather have Beyonc's talent or Jay-Z's business acumen?",
    "Would you rather be an extra in an Oscar-winning movie or the lead in a box office bomb?",
    "Would you rather vomit on your hero or have your hero vomit on you?",
    "Would you rather communicate only in emoji or never be able to text at all ever again?",
    "Would you rather be royalty 1000 years ago or an average person today?",
    "Would you rather lounge by the pool or on the beach?",
    "Would you rather wear the same socks for a month or the same underwear for a week?",
    "Would you rather work an overtime shift with your annoying boss or spend full day with your mother-in-law?",
    "Would you rather cuddle a koala or pal around with a panda?",
    "Would you rather have a sing-off with Ariana Grande or a dance-off with Rihanna?",
    "Would you rather watch nothing but Hallmark Christmas movies or nothing but horror movies?",
    "Would you rather have a pause or a rewind button in your life?",
    "Would you rather lose all your teeth or lose a day of your life every time you kissed someone?",
    "Would you rather drink from a toilet or pee in a litter box?",
    "Would you rather be forced to live the same day over and over again for a full year or take 3 years off the end of your life?",
    "Would you rather never eat watermelon ever again or be forced to eat watermelon with every meal?",
    "Would you rather go to Harvard but graduate and be jobless, or gradute from another college and work for Harvard",
]

export function get_wyr_question() {
    let randomNumber = Math.floor(Math.random() * questions.length);
    let randomQuestion = questions[randomNumber];
    return(randomQuestion);
}